### ISSUE TITLE
Package-level logging levels

### ISSUE THREAD

**Issue by mpontes** [irenical/slf4jindy#5]
Currently slf4jindy is mostly unusable since there's no way of controlling logging levels on a per-package basis. So if you want to see your code's DEBUG log statements, you're stuck seeing the DEBUG statements of every single other library that you use. The result may not be pretty.

**Comment by tiagosimao** [comment]
Indeed. I would suggest to read and dynamic listening to the 'log.level' property prefix. Creating a 'log.level.com.mycompany.mypackage=DEBUG' would activate debug log level for this package only. The semantics of the actual property 'log.level' would not be affected.
Thoughts?

**Comment by mpontes** [comment]
Yep.

**Comment by tiagosimao** [comment]
Done.
Made a small main function to fiddle with it at https://github.com/irenical/slf4jindy/blob/master/src/test/java/org/irenical/slf4j/LoggerConfigurationTest.java
